### ISSUE TITLE
Where is the libART.a file?

### ISSUE THREAD

**Issue by AngSin** [mohebifar/react-native-loader#12]
Hi I just installed react-native-loader through npm but I can't find the libART.a file. Could you please help me?

**Comment by AngSin** [comment]
This was just due to my inexperience with xcode. In case anyone else also has this problem - go to your .xcworkspace file then go to build phases. Under 'Link binary with libraries', press on '+' and select libART.a

**Comment by Balajipss** [comment]
@AngSin You saved my day!
