### ISSUE TITLE
Use prop types package from NPM

### ISSUE THREAD

**Issue by cyorobert** [mohebifar/react-native-loader#9]
Hey,

Thanks for putting this together - amazing how quickly you can get these up and running out of the box. In the remote debugger I noticed that I get the warning:

Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead.

This shouldn't be too hard to implement right?

**Comment by st0ffern** [comment]
commitizen and semantic release would fix it so you dont have to do every release manually
